import { describe, expect, test } from "vitest";
import RunnerStatusEnum from "../models/enums/runner-status-enum";
import type Runner from "../models/runner";
import {
  attribute2DRerunTrackToMatchedRunner,
  matchRunnersByName,
} from "./runners-matcher";

describe("matchRunnersByName()", () => {
  const outputRunners = matchRunnersByName(inputRunners, twoDRerunRoutes);

  const outputRunnersWithTracks = attribute2DRerunTrackToMatchedRunner(
    outputRunners,
    twoDRerunRoutes
  );

  test("to match runners by name ;)", () => {
    expect(outputRunnersWithTracks).toStrictEqual(expectedRunners);
  });
});

const expectedRunners: Runner[] = [
  {
    id: 7,
    foreignKeys: { twoDRerunRouteIndexNumber: 7 },
    status: RunnerStatusEnum.OK,
    firstName: "Max Peter",
    lastName: "Bejmer",
    startTime: 1659526560,
    time: 1896,
    legs: [],
    rank: 7,
    timeBehind: 131,
    totalTimeLost: 0,
    track: { lats: [7], lons: [7], times: [7] },
  },
  {
    id: 8,
    foreignKeys: { twoDRerunRouteIndexNumber: 8 },
    status: RunnerStatusEnum.OK,
    firstName: "Rasmus Moeller",
    lastName: "Jess",
    startTime: 1659528240,
    time: 1919,
    legs: [],
    rank: 8,
    timeBehind: 154,
    totalTimeLost: 0,
    track: { lats: [8], lons: [8], times: [8] },
  },
  {
    id: 11,
    foreignKeys: { twoDRerunRouteIndexNumber: 11 },
    status: RunnerStatusEnum.OK,
    firstName: "Nicolas",
    lastName: "Rio",
    startTime: 1659528480,
    time: 1999,
    legs: [],
    rank: 11,
    timeBehind: 234,
    totalTimeLost: 0,
    track: { lats: [11], lons: [11], times: [11] },
  },
  {
    id: 12,
    foreignKeys: { twoDRerunRouteIndexNumber: 12 },
    status: RunnerStatusEnum.OK,
    firstName: "Kristo",
    lastName: "Heinmann",
    startTime: 1659527520,
    time: 2002,
    legs: [],
    rank: 12,
    timeBehind: 237,
    totalTimeLost: 0,
    track: { lats: [12], lons: [12], times: [12] },
  },
  {
    id: 17,
    foreignKeys: { twoDRerunRouteIndexNumber: 17 },
    status: RunnerStatusEnum.OK,
    firstName: "Vegard Jarvis",
    lastName: "Westergard",
    startTime: 1659529320,
    time: 2050,
    legs: [],
    rank: 17,
    timeBehind: 285,
    totalTimeLost: 0,
    track: { lats: [17], lons: [17], times: [17] },
  },
  {
    id: 22,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Laurits Bidstrup",
    lastName: "Moller",
    startTime: 1659526200,
    time: 2107,
    legs: [],
    rank: 22,
    timeBehind: 342,
    totalTimeLost: 0,
    track: null,
  },
  {
    id: 24,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "P",
    lastName: "Llorens Caellas",
    startTime: 1659527400,
    time: 2131,
    legs: [],
    rank: 24,
    timeBehind: 366,
    totalTimeLost: 0,
    track: null,
  },
  {
    id: 45,
    foreignKeys: { twoDRerunRouteIndexNumber: 45 },
    status: RunnerStatusEnum.OK,
    firstName: "Kai Yui Hubert",
    lastName: "Yam",
    startTime: 1659525960,
    time: 5475,
    legs: [],
    rank: 45,
    timeBehind: 3710,
    totalTimeLost: 0,
    track: { lats: [45], lons: [45], times: [45] },
  },
];

const twoDRerunRoutes = [
  {
    indexnumber: 7,
    runnername: "Bejmer Max Peter",
    latarray: [7],
    lngarray: [7],
    timearray: [7],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 8,
    runnername: "Jess R Moeller",
    latarray: [8],
    lngarray: [8],
    timearray: [8],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 11,
    runnername: "Rio Nicolas",
    latarray: [11],
    lngarray: [11],
    timearray: [11],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 12,
    runnername: "Heinmann Kristo",
    latarray: [12],
    lngarray: [12],
    timearray: [12],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 17,
    runnername: "Westergard Vegard Jarvis",
    latarray: [17],
    lngarray: [17],
    timearray: [17],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 22,
    runnername: "M L Bidstrup",
    latarray: [22],
    lngarray: [22],
    timearray: [22],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 24,
    runnername: "Llorens C Pau",
    latarray: [24],
    lngarray: [24],
    timearray: [24],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
  {
    indexnumber: 45,
    runnername: "Yam Kai Yui Hubert",
    latarray: [45],
    lngarray: [45],
    timearray: [45],
    splits: [],
    zerotime: 0,
    manualsplits: 0,
  },
];

const inputRunners: Runner[] = [
  {
    id: 7,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Max Peter",
    lastName: "Bejmer",
    startTime: 1659526560,
    time: 1896,
    legs: [],
    rank: 7,
    timeBehind: 131,
    totalTimeLost: 0,
    track: null,
  },
  {
    id: 8,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Rasmus Moeller",
    lastName: "Jess",
    startTime: 1659528240,
    time: 1919,
    legs: [],
    rank: 8,
    timeBehind: 154,
    totalTimeLost: 0,
    track: null,
  },
  {
    id: 11,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Nicolas",
    lastName: "Rio",
    startTime: 1659528480,
    time: 1999,
    legs: [],
    rank: 11,
    timeBehind: 234,
    totalTimeLost: 0,
    track: null,
  },
  {
    id: 12,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Kristo",
    lastName: "Heinmann",
    startTime: 1659527520,
    time: 2002,
    legs: [],
    rank: 12,
    timeBehind: 237,
    totalTimeLost: 0,
    track: null,
  },
  {
    id: 17,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Vegard Jarvis",
    lastName: "Westergard",
    startTime: 1659529320,
    time: 2050,
    legs: [],
    rank: 17,
    timeBehind: 285,
    totalTimeLost: 0,
    track: null,
  },
  {
    id: 22,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Laurits Bidstrup",
    lastName: "Moller",
    startTime: 1659526200,
    time: 2107,
    legs: [],
    rank: 22,
    timeBehind: 342,
    totalTimeLost: 0,
    track: null,
  },
  {
    id: 24,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "P",
    lastName: "Llorens Caellas",
    startTime: 1659527400,
    time: 2131,
    legs: [],
    rank: 24,
    timeBehind: 366,
    totalTimeLost: 0,
    track: null,
  },
  {
    id: 45,
    foreignKeys: {},
    status: RunnerStatusEnum.OK,
    firstName: "Kai Yui Hubert",
    lastName: "Yam",
    startTime: 1659525960,
    time: 5475,
    legs: [],
    rank: 45,
    timeBehind: 3710,
    totalTimeLost: 0,
    track: null,
  },
];
