import { describe, expect, test } from "vitest";
import RunnerStatusEnum from "../../models/enums/runner-status-enum";
import Runner from "../../models/Runner";
import { parseIOFXML3SplitTimesFile } from "./iof-xml-3";
import { IOF_XML_2_SPLIT_TIMES } from "./mocks/iof-xml-2-split-times";
import { IOF_XML_3_SPLIT_TIMES } from "./mocks/iof-xml-3-split-times";

describe("parseIOFXML3SplitTimesFile()", () => {
  test("throw error when iof xml version is not 3.0.", () => {
    const parser = new DOMParser();
    const xmlDoc2 = parser.parseFromString(IOF_XML_2_SPLIT_TIMES, "text/xml");

    expect(() =>
      parseIOFXML3SplitTimesFile(xmlDoc2, "Men-A", "+02:00", 0)
    ).toThrow();
  });

  const parser = new DOMParser();
  const xmlDoc3 = parser.parseFromString(IOF_XML_3_SPLIT_TIMES, "text/xml");
  const runners = parseIOFXML3SplitTimesFile(xmlDoc3, "Men-A", "+02:00", 0);

  test("expecte first runner to be strict equal.", () => {
    expect(runners[0]).toStrictEqual(expectedOK);
  });

  test("expecte last runner with missing controls to be strict equal.", () => {
    expect(runners.at(-1)).toStrictEqual(expectedNotOK);
  });
});

const expectedNotOK: Runner = {
  id: 48,
  foreignKeys: {},
  status: RunnerStatusEnum.NOT_OK,
  firstName: "Angus",
  lastName: "Haines",
  startTime: 1659525360,
  time: null,
  legs: [
    {
      startControlCode: "start",
      finishControlCode: "101",
      timeOverall: 123,
      time: 123,
      rankSplit: 37,
      timeBehindSplit: 52,
      rankOverall: 37,
      timeBehindOverall: 52,
      timeBehindSuperman: 52,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "101",
      finishControlCode: "105",
      timeOverall: 798,
      time: 675,
      rankSplit: 48,
      timeBehindSplit: 535,
      rankOverall: 48,
      timeBehindOverall: 576,
      timeBehindSuperman: 587,
      isMistake: true,
      timeLoss: 471,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "105",
      finishControlCode: "107",
      timeOverall: 1489,
      time: 691,
      rankSplit: 46,
      timeBehindSplit: 482,
      rankOverall: 47,
      timeBehindOverall: 1053,
      timeBehindSuperman: 1069,
      isMistake: true,
      timeLoss: 386,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "107",
      finishControlCode: "109",
      timeOverall: 1553,
      time: 64,
      rankSplit: 39,
      timeBehindSplit: 20,
      rankOverall: 47,
      timeBehindOverall: 1071,
      timeBehindSuperman: 1089,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "109",
      finishControlCode: "110",
      timeOverall: 1682,
      time: 129,
      rankSplit: 23,
      timeBehindSplit: 25,
      rankOverall: 47,
      timeBehindOverall: 1075,
      timeBehindSuperman: 1114,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    null,
    null,
    {
      startControlCode: "115",
      finishControlCode: "116",
      timeOverall: 2044,
      time: 59,
      rankSplit: 29,
      timeBehindSplit: 14,
      rankOverall: 45,
      timeBehindOverall: 1104,
      timeBehindSuperman: 1160,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "116",
      finishControlCode: "118",
      timeOverall: 2343,
      time: 299,
      rankSplit: 40,
      timeBehindSplit: 93,
      rankOverall: 45,
      timeBehindOverall: 1197,
      timeBehindSuperman: 1253,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "118",
      finishControlCode: "121",
      timeOverall: 2448,
      time: 105,
      rankSplit: 40,
      timeBehindSplit: 35,
      rankOverall: 45,
      timeBehindOverall: 1231,
      timeBehindSuperman: 1288,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "121",
      finishControlCode: "123",
      timeOverall: 2538,
      time: 90,
      rankSplit: 41,
      timeBehindSplit: 36,
      rankOverall: 42,
      timeBehindOverall: 1224,
      timeBehindSuperman: 1324,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "123",
      finishControlCode: "125",
      timeOverall: 2723,
      time: 185,
      rankSplit: 32,
      timeBehindSplit: 49,
      rankOverall: 42,
      timeBehindOverall: 1255,
      timeBehindSuperman: 1373,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "125",
      finishControlCode: "127",
      timeOverall: 2825,
      time: 102,
      rankSplit: 9,
      timeBehindSplit: 18,
      rankOverall: 42,
      timeBehindOverall: 1327,
      timeBehindSuperman: 1391,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "127",
      finishControlCode: "130",
      timeOverall: 3078,
      time: 253,
      rankSplit: 46,
      timeBehindSplit: 136,
      rankOverall: 44,
      timeBehindOverall: 1453,
      timeBehindSuperman: 1527,
      isMistake: true,
      timeLoss: 82,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "130",
      finishControlCode: "100",
      timeOverall: 3152,
      time: 74,
      rankSplit: 44,
      timeBehindSplit: 29,
      rankOverall: 44,
      timeBehindOverall: 1480,
      timeBehindSuperman: 1556,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    null,
  ],
  rank: null,
  timeBehind: null,
  totalTimeLost: 0,
  track: null,
};

const expectedOK: Runner = {
  id: 1,
  foreignKeys: {},
  status: RunnerStatusEnum.OK,
  firstName: "Miika",
  lastName: "Kirmula",
  startTime: 1659529800,
  time: 1765,
  legs: [
    {
      startControlCode: "start",
      finishControlCode: "101",
      timeOverall: 74,
      time: 74,
      rankSplit: 2,
      timeBehindSplit: 3,
      rankOverall: 2,
      timeBehindOverall: 3,
      timeBehindSuperman: 3,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "101",
      finishControlCode: "105",
      timeOverall: 222,
      time: 148,
      rankSplit: 6,
      timeBehindSplit: 8,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 11,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "105",
      finishControlCode: "107",
      timeOverall: 475,
      time: 253,
      rankSplit: 17,
      timeBehindSplit: 44,
      rankOverall: 6,
      timeBehindOverall: 39,
      timeBehindSuperman: 55,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "107",
      finishControlCode: "109",
      timeOverall: 523,
      time: 48,
      rankSplit: 7,
      timeBehindSplit: 4,
      rankOverall: 5,
      timeBehindOverall: 41,
      timeBehindSuperman: 59,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "109",
      finishControlCode: "110",
      timeOverall: 676,
      time: 153,
      rankSplit: 39,
      timeBehindSplit: 49,
      rankOverall: 11,
      timeBehindOverall: 69,
      timeBehindSuperman: 108,
      isMistake: true,
      timeLoss: 42,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "110",
      finishControlCode: "113",
      timeOverall: 751,
      time: 75,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 8,
      timeBehindOverall: 63,
      timeBehindSuperman: 108,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "113",
      finishControlCode: "115",
      timeOverall: 948,
      time: 197,
      rankSplit: 3,
      timeBehindSplit: 1,
      rankOverall: 4,
      timeBehindOverall: 54,
      timeBehindSuperman: 109,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "115",
      finishControlCode: "116",
      timeOverall: 998,
      time: 50,
      rankSplit: 9,
      timeBehindSplit: 5,
      rankOverall: 4,
      timeBehindOverall: 58,
      timeBehindSuperman: 114,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "116",
      finishControlCode: "118",
      timeOverall: 1208,
      time: 210,
      rankSplit: 3,
      timeBehindSplit: 4,
      rankOverall: 4,
      timeBehindOverall: 62,
      timeBehindSuperman: 118,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "118",
      finishControlCode: "121",
      timeOverall: 1288,
      time: 80,
      rankSplit: 12,
      timeBehindSplit: 10,
      rankOverall: 4,
      timeBehindOverall: 71,
      timeBehindSuperman: 128,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "121",
      finishControlCode: "123",
      timeOverall: 1342,
      time: 54,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 3,
      timeBehindOverall: 28,
      timeBehindSuperman: 128,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "123",
      finishControlCode: "125",
      timeOverall: 1479,
      time: 137,
      rankSplit: 2,
      timeBehindSplit: 1,
      rankOverall: 3,
      timeBehindOverall: 11,
      timeBehindSuperman: 129,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "125",
      finishControlCode: "127",
      timeOverall: 1579,
      time: 100,
      rankSplit: 6,
      timeBehindSplit: 16,
      rankOverall: 3,
      timeBehindOverall: 81,
      timeBehindSuperman: 145,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "127",
      finishControlCode: "130",
      timeOverall: 1696,
      time: 117,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 2,
      timeBehindOverall: 71,
      timeBehindSuperman: 145,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "130",
      finishControlCode: "100",
      timeOverall: 1741,
      time: 45,
      rankSplit: 1,
      timeBehindSplit: 0,
      rankOverall: 2,
      timeBehindOverall: 69,
      timeBehindSuperman: 145,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
    {
      startControlCode: "100",
      finishControlCode: "finish",
      timeOverall: 1765,
      time: 24,
      rankSplit: 21,
      timeBehindSplit: 4,
      rankOverall: 1,
      timeBehindOverall: 0,
      timeBehindSuperman: 149,
      isMistake: false,
      timeLoss: 0,
      routeChoiceTimeLoss: null,
      detectedRouteChoice: null,
      manualRouteChoice: null,
    },
  ],
  rank: 1,
  timeBehind: 0,
  totalTimeLost: 0,
  track: null,
};
